language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="Adafruit WavePlayer Arduino Library"

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   - arduino --install-library "Adafruit Zero DMA Library"
   - arduino --install-library "Adafruit Arcada Library"
   - arduino --install-library "Adafruit Unified Sensor"
   - arduino --install-library "Adafruit NeoPixel"
   - arduino --install-library "Adafruit ADT7410 Library"
   - arduino --install-library "Adafruit GFX Library"
   - arduino --install-library "Adafruit ST7735 and ST7789 Library"
   - arduino --install-library "Adafruit ILI9341"
   - arduino --install-library "Adafruit SPIFlash"
   - arduino --install-library "Adafruit LIS3DH"
   - arduino --install-library "Adafruit ZeroTimer Library"
   - arduino --install-library "Adafruit TouchScreen"
   - arduino --install-library "Adafruit MSA301"
   - arduino --install-library "Adafruit BusIO"
   - arduino --install-library "Adafruit PixelDust"
   - arduino --install-library "ArduinoJson"
   - arduino --install-library "Adafruit ImageReader Library"
   - arduino --install-library "Adafruit TinyUSB Library"
   - arduino --install-library "SdFat - Adafruit Fork"
   - arduino --install-library "Adafruit Circuit Playground"

script:
   - build_samd_platforms

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
